Repository NguyenNC-VJP/test, pull requests merged in 2025-05, with the labels that each got.

#3 Develop
  manage.py
  mysite/__init__.py
  mysite/asgi.py
  mysite/settings.py
  mysite/urls.py
  mysite/wsgi.py
  requirements.txt
Labels: Môi trường

#7 merge Feature/login nguyen into develop
  GIT_WORKFLOW.md
  README.md
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/models.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  manage.py
  mysite/settings.py
  mysite/urls.py
Labels: feature, develop

#10 merge develop into main
  Git-workflow.md
  README.md
Labels: main

#11 fix: file.md
  Git-workflow.md
Labels: hotfix

#13 Feature/be login api
  mysite/backend.md
  mysite/khongthang.md
Labels: feature
